dataset:
  train:
    target: uci_har_us
    arguments:
      train: true
      class_balance: false
  test:
    target: uci_har_us
    arguments:
      train: false
      class_balance: false

client:
  target: CentralizedClient
  training_engine:
    target: TrainingEngine
    arguments:
      optimizer: SGD
      epochs: 5
      lr: 0.001
      optimizer: SGD
      sgd_momentum: 0.9
      training_batch_size: 32
      validation_batch_size: 128
  local_model:
    target: UCI_HAR_US_Net
